name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      # - name: Check Format
      #   id: npm-format-check
      #   run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup-node
        run: sudo apt-get install -y curl wget
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: 'Scan test image'
        uses: ./
        id: test-action
        with:
          path: './'
          grype-version: v0.73.4 # set the same version to test that current Grype binary wasn't overwritten by the latest version
          fail-build: false # to prevent fail due to vuln:s on test image

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
